services:
  - type: web
    name: student-union-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build && npm run render-postbuild
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false  # سيتم إضافته يدوياً في Render
      - key: JWT_SECRET
        sync: false  # سيتم إضافته يدوياً في Render
